language: php

php:
  - 5.4
  - 5.5
  - 5.6

install:
  - composer self-update
  - composer install --dev

before_script:
  - phpenv rehash
  - set +H

script:
  - phpunit

notifications:
  email: false
